controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute


app_account_delete:
  path: /account/delete
  controller: App\Controller\ProfileController::deleteAccount
  methods: [POST]

