nelmio_cors:
  defaults:
    allow_origin: [ '*' ]
    allow_credentials: true
    allow_headers: [ '*' ]
    expose_headers: [ 'Link' ]
    allow_methods: [ '*' ]
    max_age: 3600
  paths:
    '^/':
      allow_origin: [ '*' ]